replicaCount: 3

image:
  repository: ghcr.io/chmenegatti/bolao-da-copa
  tag: latest
  pullPolicy: Always

database:
  secretName: pg-auth-prod
  host: palpite-prod-db-rw
  port: 5432
  name: palpite_prod

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

env:
  NODE_ENV: production
  NEXTAUTH_URL: http://palpite.local
  ADMIN_EMAIL: admin@bolao.com

secrets:
  AUTH_SECRET: "diUJLjXKH//qicYi6C3VsYsjvQWcx/9qmE7yEeQq9f8="