apiVersion: apps/v1
kind: Deployment
metadata:
  name: palpite-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: palpite-app
  template:
    metadata:
      labels:
        app: palpite-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}

            - name: NEXTAUTH_URL
              value: {{ .Values.env.NEXTAUTH_URL | quote }}

            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: palpite-app-secret
                  key: AUTH_SECRET

            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: palpite-app-secret
                  key: ADMIN_PASS

            - name: ADMIN_EMAIL
              value: {{ .Values.env.ADMIN_EMAIL | quote }}

            # 🔥 DB (CloudNativePG)
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName | quote }}
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName | quote }}
                  key: password

            - name: DB_NAME
              value: {{ .Values.database.name | quote }}

            - name: DATABASE_URL
              value: {{ printf "postgresql://$(DB_USER):$(DB_PASSWORD)@%s:%v/$(DB_NAME)?schema=public" .Values.database.host .Values.database.port | quote }}

          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"