apiVersion: apps/v1
kind: Deployment
metadata:
  name: palpite-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: palpite-app
  template:
    metadata:
      labels:
        app: palpite-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV }}

            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: palpite-app-secret
                  key: NEXTAUTH_URL

            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: palpite-app-secret
                  key: AUTH_SECRET

            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: palpite-app-secret
                  key: ADMIN_EMAIL

            # 🔥 DB (CloudNativePG)
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-auth-prod
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-auth-prod
                  key: password

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-auth-prod
                  key: dbname

            - name: DATABASE_URL
              value: postgresql://$(DB_USER):$(DB_PASSWORD)@palpite-prod-db-rw:5432/$(DB_NAME)?schema=public

          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"