apiVersion: v1
kind: Secret
metadata:
  name: palpite-app-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  AUTH_SECRET: {{ .Values.secrets.AUTH_SECRET | quote }}