apiVersion: v1
kind: Secret
metadata:
  name: palpite-app-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AUTH_SECRET: {{ default "" .Values.secrets.AUTH_SECRET | b64enc }}
  NEXTAUTH_URL: {{ default "" .Values.secrets.NEXTAUTH_URL | b64enc }}
  ADMIN_EMAIL: {{ default "admin@bolao.com" .Values.secrets.ADMIN_EMAIL | b64enc }}